{% set name = "nuget-license" %}
{% set version = "3.0.13" %}

package:
  name: {{ name|lower }}
  version: "{{ version.replace('-', '_') }}"

source:
  url: https://github.com/sensslen/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8b0bcfb0814f5a8007e79ea0e8f2bf909c48962712ea7934c316689a008d1c7c

build:
  noarch: generic
  number: 0

requirements:
  build:
    - sed
  host:
    - dotnet
  run:
    - dotnet

test:
  commands:
    - dotnet-project-licenses --help

about:
  home: https://github.com/sensslen/{{ name }}
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: .NET Core tool to print or save all the licenses of a project
  dev_url: https://github.com/sensslen/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
