{% set name = "nuget-license" %}
{% set version = "3.0.9" %}

package:
  name: {{ name|lower }}
  version: "{{ version.replace('-', '_') }}"

source:
  url: https://github.com/sensslen/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 611926dd38a33265261847fc530b6771b48ab45461c4c49b667da9e7d9ea2029

build:
  noarch: generic
  number: 0

requirements:
  build:
    - sed
  host:
    - dotnet
  run:
    - dotnet

test:
  commands:
    - dotnet-project-licenses --help

about:
  home: https://github.com/sensslen/{{ name }}
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: .NET Core tool to print or save all the licenses of a project
  dev_url: https://github.com/sensslen/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
