{% set name = "nuget-license" %}
{% set version = "3.0.7" %}

package:
  name: {{ name|lower }}
  version: "{{ version.replace('-', '_') }}"

source:
  url: https://github.com/sensslen/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4021e47ff809aa0e88a278da0b5f6823055294563df7a7358fff36f3a7607d1c

build:
  noarch: generic
  number: 0

requirements:
  build:
    - sed
  host:
    - dotnet
  run:
    - dotnet

test:
  commands:
    - dotnet-project-licenses --help

about:
  home: https://github.com/sensslen/{{ name }}
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: .NET Core tool to print or save all the licenses of a project
  dev_url: https://github.com/sensslen/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
