{% set name = "nuget-license" %}
{% set version = "3.0.6" %}

package:
  name: {{ name|lower }}
  version: "{{ version.replace('-', '_') }}"

source:
  url: https://github.com/sensslen/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d8a9168c740756e4b645c77c7a8468cccd6cee60b9a2129b391268b0960dd41c

build:
  noarch: generic
  number: 0

requirements:
  build:
    - sed
  host:
    - dotnet
  run:
    - dotnet

test:
  commands:
    - dotnet-project-licenses --help

about:
  home: https://github.com/sensslen/{{ name }}
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: .NET Core tool to print or save all the licenses of a project
  dev_url: https://github.com/sensslen/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
