context:
  version: "4.0.12"

package:
  name: nuget-license
  version: ${{ version }}

source:
  url: https://github.com/sensslen/nuget-license/archive/v${{ version }}.tar.gz
  sha256: b68b298b2f311efaedb2447768ae51e5ab0afa1bcb36f4a46ed8dc4c7fe2f5f3

build:
  number: 0
  noarch: generic

requirements:
  build:
    - sed
  host:
    - dotnet
  run:
    - dotnet

tests:
  - script:
      - dotnet-project-licenses --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: .NET Core tool to print or save all the licenses of a project
  homepage: https://github.com/sensslen/nuget-license
  repository: https://github.com/sensslen/nuget-license

extra:
  recipe-maintainers:
    - danielnachun
