context:
  version: "3.1.3"

package:
  name: nuget-license
  version: ${{ version }}

source:
  url: https://github.com/sensslen/nuget-license/archive/v${{ version }}.tar.gz
  sha256: 375f08effd5336297f2530070c445b63a4a617830d8310e549e2121406494ad9

build:
  number: 0
  noarch: generic

requirements:
  build:
    - sed
  host:
    - dotnet
  run:
    - dotnet

tests:
  - script:
      - dotnet-project-licenses --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: .NET Core tool to print or save all the licenses of a project
  homepage: https://github.com/sensslen/nuget-license
  repository: https://github.com/sensslen/nuget-license

extra:
  recipe-maintainers:
    - danielnachun
