context:
  version: "3.1.7"

package:
  name: nuget-license
  version: ${{ version }}

source:
  url: https://github.com/sensslen/nuget-license/archive/v${{ version }}.tar.gz
  sha256: e5571a33ba92ae0ce18ad1c310fae2b4ce2e570e223d8bde16dfc1f60dcae046

build:
  number: 0
  noarch: generic

requirements:
  build:
    - sed
  host:
    - dotnet
  run:
    - dotnet

tests:
  - script:
      - dotnet-project-licenses --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: .NET Core tool to print or save all the licenses of a project
  homepage: https://github.com/sensslen/nuget-license
  repository: https://github.com/sensslen/nuget-license

extra:
  recipe-maintainers:
    - danielnachun
